"""Deterministic MockLLMProvider.

Returns canned responses keyed by a light prompt-classification heuristic.
Every mock output is prefixed with a visible "[MOCK]" marker so no downstream
stage can silently ship mock text as real.
"""
from __future__ import annotations

import hashlib
from typing import Any

from .base import LLMProvider, LLMResponse


MOCK_BANNER = "[MOCK] This text is generated by MockLLMProvider. Replace with real LLM for production."


def _route(prompt: str) -> str:
    lower = prompt.lower()
    if "reviewer" in lower or "audit" in lower:
        return "review"
    if "part tutor" in lower or "teaching note" in lower:
        return "part_note"
    if "course map" in lower or "curriculum" in lower:
        return "course_map"
    if "formula" in lower:
        return "formula"
    if "example" in lower:
        return "example"
    if "visual" in lower:
        return "visual"
    return "generic"


def _short_hash(prompt: str) -> str:
    return hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:8]


class MockLLMProvider(LLMProvider):
    name = "mock"

    def generate(self, prompt: str, **kwargs: Any) -> LLMResponse:
        kind = _route(prompt)
        h = _short_hash(prompt)
        body = {
            "review": f"{MOCK_BANNER}\n\n- finding: ensure source_refs attached.\n- finding: verify formula units.\n- id: {h}",
            "part_note": f"{MOCK_BANNER}\n\n## 1. 这部分解决什么问题\n(mock) placeholder paragraph. id={h}\n\n## 5. 公式、变量、单位与适用条件\n(mock) placeholder formula description.\n",
            "course_map": f"{MOCK_BANNER}\n\n# Course Map (mock)\n- module A\n- module B\nid={h}",
            "formula": f"{MOCK_BANNER}\n\nformula description (mock). id={h}",
            "example": f"{MOCK_BANNER}\n\nexample walk-through (mock). id={h}",
            "visual": f"{MOCK_BANNER}\n\nvisual plan (mock). id={h}",
            "generic": f"{MOCK_BANNER}\n\ngeneric mock response id={h}",
        }[kind]
        return LLMResponse(text=body, model="mock", usage={"route": kind}, warnings=[])
